/**
 * Blog post registry.
 *
 * Posts can come from two places:
 *  1. JSON files in apps/web/content/blog/<slug>.json — the primary store.
 *     Generated by apps/web/scripts/blog-daily/run.py (daily cron).
 *  2. Inline legacy posts below — empty for now (the original 5 posts
 *     were migrated to JSON on 2026-06-18 by the migrate_inline_to_json
 *     script). Kept as an INLINE_POSTS array so future hand-written
 *     posts can sit alongside generated ones for editorial review.
 *
 * We merge both so the blog index and post pages render everything
 * regardless of source. Inline posts take precedence if a slug is
 * duplicated (allows manual overrides of generated content).
 *
 * Why JSON for generated posts:
 *   The daily cron is Python. Writing TS modules via string manipulation
 *   is fragile. JSON files are the right format for typed data that
 *   isn't code, and they let lib/blog.ts stay the single load path.
 *
 * IMPORTANT — every fact in `content` (or in the page bodies we write)
 * must be sourceable. We do NOT make up statistics, prices, dates, or
 * "studies show" claims. Where we reference our own product behaviour,
 * the source is the deployed API at https://api.getpdfpro.com (verified
 * live) and the live web app at https://app.getpdfpro.com.
 *
 * Posts use a simple structured `sections` model rather than freeform
 * markdown. The renderer handles the conversion. This keeps the data
 * typed, the post format consistent, and prevents layout bugs from
 * malformed markdown.
 *
 * To add a hand-written post:
 *   1. Drop apps/web/content/blog/<slug>.json with the post data
 *   2. Drop apps/web/public/blog/cover-<slug>.webp (1280x720)
 *   3. The post is auto-discovered by getAllPosts() / getPostBySlug()
 *
 * Or: add an entry to INLINE_POSTS below for editorial overrides.
 */

import fs from "node:fs";
import path from "node:path";

export type BlogSection =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "code"; lang?: string; code: string }
  | { type: "callout"; tone: "info" | "tip" | "warning"; text: string }
  | { type: "table"; headers: string[]; rows: string[][] };

export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  excerpt: string;
  cover: string;
  date: string;
  author: string;
  readingMinutes: number;
  tags: string[];
  sections: BlogSection[];
  sources: { label: string; url: string; accessedOn: string }[];
};

/**
 * Hand-written editorial overrides. Empty by default. Add a post here
 * only if you want it to win over a generated post with the same slug
 * (useful for fixing a bad generation, or for hand-penned flagship posts).
 */
const INLINE_POSTS: BlogPost[] = [];

/**
 * Load generated posts from apps/web/content/blog/<slug>.json at module
 * init. Runs at build time (Next.js statically renders this).
 *
 * Skips:
 *   - Files starting with `_` (used for _review/ and similar)
 *   - Files that fail validation (logged to console as a warning)
 */
function loadGeneratedPosts(): BlogPost[] {
  const contentDir = path.join(process.cwd(), "apps", "web", "content", "blog");
  if (!fs.existsSync(contentDir)) return [];

  const posts: BlogPost[] = [];
  for (const file of fs.readdirSync(contentDir)) {
    if (!file.endsWith(".json")) continue;
    if (file.startsWith("_")) continue;
    const slug = file.replace(/\.json$/, "");
    const fullPath = path.join(contentDir, file);
    try {
      const raw = fs.readFileSync(fullPath, "utf-8");
      const post = JSON.parse(raw) as BlogPost;
      // Minimal validation
      if (!post.slug || !post.title || !post.sections) {
        console.warn(
          `[lib/blog] skipping ${file}: missing required fields (slug, title, sections)`,
        );
        continue;
      }
      if (post.slug !== slug) {
        console.warn(
          `[lib/blog] skipping ${file}: slug mismatch (file=${slug}, json=${post.slug})`,
        );
        continue;
      }
      posts.push(post);
    } catch (err) {
      console.warn(`[lib/blog] failed to load ${file}: ${err}`);
    }
  }
  return posts;
}

const GENERATED_POSTS: BlogPost[] = loadGeneratedPosts();

/**
 * All posts, deduped (inline wins over generated if same slug), sorted
 * newest first.
 */
const POSTS: BlogPost[] = (() => {
  const bySlug = new Map<string, BlogPost>();
  // Generated first so inline (if present) overrides
  for (const p of GENERATED_POSTS) bySlug.set(p.slug, p);
  for (const p of INLINE_POSTS) bySlug.set(p.slug, p);
  return Array.from(bySlug.values());
})();

export function getAllPosts(): BlogPost[] {
  // Sort newest first
  return [...POSTS].sort((a, b) => (a.date < b.date ? 1 : -1));
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return POSTS.map((p) => p.slug);
}

/**
 * Look up the blog post that targets a specific tool, by tool slug.
 *
 * The daily cron writes posts with the pattern `<toolSlug>-guide.json`
 * (e.g. merge-guide.json for the Merge tool). This helper lets the
 * tool pages (`/tools/<slug>`) link to the related blog post when one
 * exists, and render nothing if there isn't one yet.
 *
 * The lookup is "slug + -guide" so we don't break if the cron ever
 * changes the suffix.
 */
export function getGuideForTool(toolSlug: string): BlogPost | undefined {
  const target = `${toolSlug}-guide`;
  return POSTS.find((p) => p.slug === target);
}
