#!/usr/bin/env bash
#
# deploy_well_known.sh — copy the mobile-app Universal Links / App
# Links templates to the web app's `.well-known/` directory so the
# static host (Cloudflare Pages / Vercel) serves them at the
# well-known paths Apple and Google scrape.
#
# Files deployed:
#   - apps/web/public/.well-known/apple-app-site-association (iOS)
#   - apps/web/public/.well-known/assetlinks.json          (Android)
#
# Source of truth lives in getpdfpro/apps/mobile/platform_setup/
# (the project doesn't ship ios/ and android/ in git — see
# platform_setup/apply.sh for the dev-side equivalent).
#
# Run this:
#   1. Once when you first set up Universal Links / App Links.
#   2. Every time you rotate the upload keystore (the SHA-256
#      fingerprint in assetlinks.json changes, and Android will
#      silently fail App Links verification without an update).
#   3. Every time you ship a new bundle ID or team ID (the iOS
#      file is regenerated by the Apple developer portal).
#
# The web app is committed at apps/ (sibling of getpdfpro/), so we
# resolve the path from this script's location.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/../../.." && pwd)"
WEB_PUBLIC="$REPO_ROOT/apps/web/public/.well-known"
SOURCE_DIR="$MOBILE_DIR/platform_setup"

# iOS side — the apple-app-site-association file. Apple wants the
# `applicationid` (iOS bundle ID) and the `paths` we want to claim
# (typically `*` for everything). The `applinks:app.getpdfpro.com`
# entry in ios/Runner/Runner.entitlements mirrors this.
ASSET_LINKS_IOS="$SOURCE_DIR/../ios/apple-app-site-association.template"

# Android side — the assetlinks.json file we already ship in
# platform_setup/android/. Replace the placeholder SHA-256
# fingerprint before deploying (see android/key.properties.example
# for how to extract the real one).
ASSET_LINKS_ANDROID="$SOURCE_DIR/android/assetlinks.json"

# Sanity check
if [ ! -f "$ASSET_LINKS_ANDROID" ]; then
  echo "Error: $ASSET_LINKS_ANDROID not found." >&2
  echo "Run from the repo root or fix the path resolution." >&2
  exit 1
fi

if [[ "$ASSET_LINKS_ANDROID" == *"REPLACE_ME"* ]]; then
  echo "WARNING: $ASSET_LINKS_ANDROID still has REPLACE_ME in it." >&2
  echo "Android App Links will fail to verify until you replace it." >&2
  echo "Run:  keytool -list -v -keystore android/app/upload-keystore.jks" >&2
  echo "Then edit $ASSET_LINKS_ANDROID and re-run this script." >&2
  echo ""
fi

mkdir -p "$WEB_PUBLIC"

# Deploy iOS — only if a template exists. Apple's portal regenerates
# this file whenever you add a new associated domain, so sometimes
# the canonical source lives there, not in this repo.
if [ -f "$ASSET_LINKS_IOS" ]; then
  echo "==> Deploying apple-app-site-association"
  cp "$ASSET_LINKS_IOS" "$WEB_PUBLIC/apple-app-site-association"
else
  echo "Note: no apple-app-site-association template found at"
  echo "      $ASSET_LINKS_IOS"
  echo "      (Apple regenerates this on developer.apple.com — paste"
  echo "       the output into apps/web/public/.well-known/ manually)"
fi

echo "==> Deploying assetlinks.json"
cp "$ASSET_LINKS_ANDROID" "$WEB_PUBLIC/assetlinks.json"

echo ""
echo "Done. Verify the deploy:"
echo "  curl -sI https://app.getpdfpro.com/.well-known/assetlinks.json"
echo "  curl -sI https://app.getpdfpro.com/.well-known/apple-app-site-association"
echo "  open https://developers.google.com/digital-asset-links/tools/generator"
echo "  open https://search.google.com/test/rich-results  (for iOS validation)"
echo ""
echo "Commit + push the changes in apps/web/public/.well-known/ when ready."
